// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxapvtqxbeentcfvwuel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4YXB2dHF4YmVlbnRjZnZ3dWVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNzY0MTksImV4cCI6MjA3MTc1MjQxOX0.o2FzXX3i24Zw0q6bQ6WdQn6QDBGDORF6UGCEXXC-gc4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});